DEFAULT_EXPLOSION_RADIUS = 3
PERK_TIME = 30
RADIUS_PERK_INCREASE = 2
REMOTE_PERK_COUNT = 3

PREDICTOR_DEEP = 5

ESTIMATION_AROUND_K = 0.2
ESTIMATION_ACK_MIN_SCORE = 0.75

DIRECTION_STOP_K = 0.7
DIRECTION_INVERTED_K = 0.8

MAX_BOARD_DIFF = 5
